plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/zzx/WorkBuddy/2026-05-12-task-13/exam-system"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]